In [1]:
import numpy as np
import pandas as pd
from sklearn.linear_model import LinearRegression
from sklearn.utils import shuffle

In [3]:
data = pd.read_csv('student-mat.csv')
data.head()

school sex  age address famsize Pstatus  ...  Walc  health absences  G1  G2  G3
0     GP   F   18       U     GT3       A  ...     1       3        6   5   6   6
1     GP   F   17       U     GT3       T  ...     1       3        4   5   5   6
2     GP   F   15       U     LE3       T  ...     3       3       10   7   8  10
3     GP   F   15       U     GT3       T  ...     1       5        2  15  14  15
4     GP   F   16       U     GT3       T  ...     2       5        4   6  10  10

[5 rows x 33 columns]

In [4]:
data = data[['G1', 'G2', 'G3', 'studytime', 'failures', 'absences']]
predict = 'G3'
x = np.array(data.drop([predict], 1))
y = np.array(data[predict])

In [5]:
from sklearn.model_selection import train_test_split
xtrain, xtest, ytrain, ytest = train_test_split(x, y, test_size=0.2)

In [6]:
linear_regression = LinearRegression()
linear_regression.fit(xtest, ytest)
accuracy = linear_regression.score(xtest, ytest)
print(accuracy)

0.8631025830469388


In [7]:
predictions = linear_regression.predict(xtest)

for i in range(len(predictions)):
    print(predictions[x], xtest[x], [ytest[x]])

[[13.70109893 10.23224831 11.08266833 11.85932998 10.23224831]
 [13.70109893 13.70109893 11.08266833 11.85932998  8.17827011]
 [10.40224498  4.53679861 11.08266833  9.17144007 12.83439706]
 ...
 [12.83439706  4.53679861 12.97435501  9.17144007  9.17144007]
 [12.50210887 13.21964058 12.97435501 11.85932998 11.85932998]
 [ 4.53679861  9.65314402 12.97435501 11.85932998 13.70109893]] [[[13 13  2  0 23]
  [11 11  4  0  0]
  [13 11  3  0  8]
  [12 12  2  0  2]
  [11 11  4  0  0]]

 [[13 13  2  0 23]
  [13 13  2  0 23]
  [13 11  3  0  8]
  [12 12  2  0  2]
  [10  9  4  0  0]]

 [[10 11  4  0 10]
  [ 7  7  2  1  0]
  [13 11  3  0  8]
  [13 10  2  1 22]
  [14 12  2  0 20]]

 ...

 [[14 12  2  0 20]
  [ 7  7  2  1  0]
  [13 13  2  0  2]
  [13 10  2  1 22]
  [13 10  2  1 22]]

 [[14 12  1  0  4]
  [14 13  2  0  4]
  [13 13  2  0  2]
  [12 12  2  0  2]
  [12 12  2  0  2]]

 [[ 7  7  2  1  0]
  [11 10  3  0  4]
  [13 13  2  0  2]
  [12 12  2  0  2]
  [13 13  2  0 23]]] [array([[13, 11, 11, 11, 11]